<<<<<<< HEAD
<<<<<<< HEAD
(window.webpackJsonp=window.webpackJsonp||[]).push([[3],{20:function(e,t,n){"use strict";n.r(t);var o=n(0),r=n.n(o);n(31);function i(e){return(i="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}function s(e,t){for(var n=0;n<t.length;n++){var o=t[n];o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(e,o.key,o)}}function a(e,t){return!t||"object"!==i(t)&&"function"!=typeof t?function(e){if(void 0===e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return e}(e):t}function u(e){return(u=Object.setPrototypeOf?Object.getPrototypeOf:function(e){return e.__proto__||Object.getPrototypeOf(e)})(e)}function c(e,t){return(c=Object.setPrototypeOf||function(e,t){return e.__proto__=t,e})(e,t)}var l=function(e){function t(){return function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}(this,t),a(this,u(t).apply(this,arguments))}return function(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function");e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,writable:!0,configurable:!0}}),t&&c(e,t)}(t,o["Component"]),function(e,t,n){t&&s(e.prototype,t),n&&s(e,n)}(t,[{key:"render",value:function(){return r.a.createElement("section",{className:"container about-section",id:"about"},r.a.createElement("h2",null,"About"),r.a.createElement("p",null,"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."))}}]),t}();t.default=l},31:function(e,t,n){var o=n(32);"string"==typeof o&&(o=[[e.i,o,""]]);var r={hmr:!0,transform:void 0,insertInto:void 0};n(5)(o,r);o.locals&&(e.exports=o.locals)},32:function(e,t,n){(e.exports=n(4)(!1)).push([e.i,".about-section{padding:2%;margin-top:30vh;height:100vh;display:flex;align-items:center;justify-content:center;flex-direction:column}\n",""])}}]);
=======
(window.webpackJsonp=window.webpackJsonp||[]).push([[3],{31:function(n,e,t){"use strict";t.r(e);var a=t(0),o=t.n(a);t(40);e.default=function(){return o.a.createElement("div",{className:"page"},o.a.createElement("h1",null,"404"),o.a.createElement("p",null,"Page not found!"))}},40:function(n,e,t){var a=t(41);"string"==typeof a&&(a=[[n.i,a,""]]);var o={hmr:!0,transform:void 0,insertInto:void 0};t(10)(a,o);a.locals&&(n.exports=a.locals)},41:function(n,e,t){(n.exports=t(9)(!1)).push([n.i,".page{background:white}\n",""])}}]);
>>>>>>> Updates
=======
(window.webpackJsonp=window.webpackJsonp||[]).push([[3],{23:function(n,e,t){"use strict";t.r(e);var a=t(0),o=t.n(a);t(40);e.default=function(){return o.a.createElement("div",{className:"page"},o.a.createElement("h1",null,"404"),o.a.createElement("p",null,"Page not found!"))}},40:function(n,e,t){var a=t(41);"string"==typeof a&&(a=[[n.i,a,""]]);var o={hmr:!0,transform:void 0,insertInto:void 0};t(7)(a,o);a.locals&&(n.exports=a.locals)},41:function(n,e,t){(n.exports=t(6)(!1)).push([n.i,".page{background:white}\n",""])}}]);
>>>>>>> Updates
