version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - flexsearch
  - fontsource
  - frontmatter
  - prismjs
  - raleway
  - rishiikc
  - rishikc
  - Typegen
ignoreWords: []
import: []
