version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - flexsearch
  - fontsource
  - frontmatter
  - gtag
  - itemprop
  - mukta
  - newtab
  - prismjs
  - rishiikc
  - rishikc
  - tailwindcss
  - Typegen
ignoreWords: []
import: []
