version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Dribbble
  - flexsearch
  - fontsource
  - frontmatter
  - gtag
  - insta
  - itemprop
  - mukta
  - newtab
  - nofollow
  - noopener
  - noreferrer
  - nprogress
  - prismjs
  - rishiikc
  - rishikc
  - tailwindcss
  - Typegen
  - webp
ignoreWords: []
import: []
